# Generated by Django 3.1.1 on 2020-09-16 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='آدرس مقاله')),
                ('description', models.TextField(verbose_name='محتوای مقاله')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images', verbose_name='عکس مقاله')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس')], max_length=1, verbose_name='وضعیت')),
            ],
        ),
    ]
